# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "app".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose

services:
  jenkins:
    image: jenkins_sudoku_image:2.528.3
    container_name: jenkins_sudoku_container

    # ensure Jenkins runs with UID/GID matching host mount
    user: "2000:2000"

    environment:
      TZ: Europe/Paris
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"

    restart: unless-stopped

    ports:
      - "8080:8080"
      - "50000:50000"

    volumes:
      # Mount the WSL2 ext4 host folder for Jenkins home
      - /home/mirko/jenkins_home_host_mount:/var/jenkins_home
      # Needed to allow Docker-in-Docker usage
      - /var/run/docker.sock:/var/run/docker.sock
